import { milesToMeters } from '../core/units.js';
import { runSimulation } from '../core/modes.js';
const $=id=>document.getElementById(id); let mode='research';
const fmt=(n,d=3)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(n);
const power=w=>w>=1e12?`${fmt(w/1e12)} TW`:w>=1e9?`${fmt(w/1e9)} GW`:w>=1e6?`${fmt(w/1e6)} MW`:`${fmt(w/1e3)} kW`;
function input(){return {fieldMVPerM:+$('field').value,verticalLengthM:milesToMeters(+$('length').value),log10BeamRate:+$('rate').value,geometry:$('geometry').value,useIdealizedHelix:$('helix').checked,helixTurns:+$('turns').value,helixRadiusM:+$('radius').value,moonLoop:{minimumScaleFactor:0,ricciScalar:Infinity,kretschmannScalar:Infinity,enablePhenomenologicalBounce:false,bounceConditionSatisfied:false},playground:{superstorm:true,seed:14}}}
function render(){const data=runSimulation(mode,input()),s=data.standardResult??data, b=s.beam,c=s.collision;$('fieldOut').textContent=`${$('field').value} MV/m`;$('lengthOut').textContent=`${$('length').value} mi`;$('rateOut').textContent=`10^${$('rate').value} p/s`;$('turnsOut').textContent=$('turns').value;$('radiusOut').textContent=`${$('radius').value} m`;$('helixOptions').classList.toggle('hidden',!$('helix').checked);
$('energy').textContent=`${fmt(b.kineticEnergyGeV)} GeV`;$('energyJ').textContent=`${b.kineticEnergyJ.toExponential(3)} J`;$('speed').textContent=`${fmt(b.beta*100,9)}% c`;$('gamma').textContent=`γ = ${fmt(b.gamma)}`;$('com').textContent=`${fmt(c.centerOfMassGeV)} GeV`;$('geometryNote').textContent=c.geometry==='head-on'?'Two moving beams':'Fixed target';$('power').textContent=power(s.powerW);$('accessibility').innerHTML=s.accessibility.map(x=>`<div class="${x.accessible?'yes':''}"><b>${x.accessible?'✓':'○'} ${x.name}</b><small> threshold ${x.thresholdGeV===Infinity?'heavy-ion model':x.thresholdGeV+' GeV'}</small><p>${x.note}</p></div>`).join('');
const panel=$('modePanel'); if(mode==='research')panel.innerHTML='<h2>Research Lab</h2><p>Only the shared, documented kinematics are authoritative here. Collision event generation, detector response, trigger, reconstruction and cross sections are intentionally shown as not implemented.</p>';if(mode==='moon-loop'){const m=data.moonLoop;panel.innerHTML=`<h2>Moon-Loop Experimental</h2><p>${m.classification}</p>${m.tests.map(t=>`<p><span class="status ${t.status.toLowerCase().replaceAll(' ','-')}">${t.status}</span> <b>${t.name}</b> — ${t.detail}</p>`).join('')}<h3>Known limits</h3><ul>${m.limitations.map(x=>`<li>${x}</li>`).join('')}</ul>`}if(mode==='playground')panel.innerHTML=`<h2>Collider Playground</h2><p>Fun presentation layered over the unchanged standard result.</p>${data.gameCards.map(x=>`<p><span class="status">${x.label}</span> <b>${x.name}</b><br><small>Real: ${x.real} Game: ${x.fiction}</small></p>`).join('')}`;
$('provenance').innerHTML=`<p><b>Model:</b> ${s.provenance.model}</p><p><b>Assumptions:</b> ${s.provenance.assumptions.join('; ')}.</p><p><b>Current limitations:</b> ${s.limitations.join(' ')}</p>`;}
for(const el of document.querySelectorAll('input,select'))el.addEventListener('input',render);for(const el of document.querySelectorAll('button[data-mode]'))el.addEventListener('click',()=>{mode=el.dataset.mode;document.querySelectorAll('button[data-mode]').forEach(x=>x.classList.toggle('active',x===el));$('mode-description').textContent=mode==='research'?'Established special-relativistic kinematics':mode==='moon-loop'?'Same baseline + explicit hypothesis tests':'Same baseline + labeled game mechanics';render()});render();
